### ISSUE TITLE
how did you handle heroku:domains add?

### ISSUE THREAD

**Issue by JMIdeaMaker** [warrenguy/heroku-sinatra-hidden-service#2]
Before a CNAME record routed to a herokuapp domain can work, a user needs to run the `heroku domains:add` command. How did you manage that with an onion url?

**Comment by warrenguy** [comment]
It's not being routed by Heroku. A Tor process runs on the dyno and passes connections directly to the `server_port` specified.

**Comment by JMIdeaMaker** [comment]
How does it do that?

**Comment by warrenguy** [comment]
take a look at https://github.com/warrenguy/ruby-hidden-service
